<div class="table-header" >
    <div class="pull-left">
        <header>
            <h4 class="pull-left">
                Users (<span ng-bind="userCtrl.recordsFiltered"></span>)
            </h4>
        </header>
    </div>

    <div class="pull-right">
        
        <a uib-popover="Reset all page filters and re-populate results" popover-placement="bottom" popover-trigger="'mouseenter'" class="table-header-btn reset-filters-btn btn-default" title="Reset Filters" ng-click="userCtrl.resetFilters()"> 
            Reset all filters
            <i class="ion-close"></i>
        </a>

        <div class="btn-group bootstrap-select itemPerPage form-control" uib-dropdown>

            <button class="btn dropdown-toggle btn-default" type="button" 
                    uib-dropdown-toggle title="Set Page Size" >

                <span class="filter-option pull-left" ng-bind="userCtrl.pageSize"> 
                   
                </span>

                <span class="caret"></span>

            </button>

            <ul class="dropdown-menu" uib-dropdown-menu role="menu" >
                <li >
                    <a href="#" ng-click="userCtrl.selectPageSize(salespeopleCtrl.pageSizes[0])" ng-bind="userCtrl.pageSizes[0]"></a>
                </li>
                <li >
                    <a href="#" ng-click="userCtrl.selectPageSize(salespeopleCtrl.pageSizes[1])" ng-bind="userCtrl.pageSizes[1]"></a>
                </li>
                <li >
                    <a href="#" ng-click="userCtrl.selectPageSize(salespeopleCtrl.pageSizes[2])" ng-bind="userCtrl.pageSizes[2]"></a>
                </li>
                <li >
                    <a href="#" ng-click="userCtrl.selectPageSize(salespeopleCtrl.pageSizes[3])" ng-bind="userCtrl.pageSizes[3]"></a>
                </li>
                <li >
                    <a href="#" ng-click="userCtrl.selectPageSize(userCtrl.pageSizes[4])" ng-bind="userCtrl.pageSizes[4]"></a>
                </li>
            </ul>

        </div>

        <div class="table-header-text">Users</div>

        <div class="dataTables_paginate paging_bootstrap pull-right">

            <ul uib-pagination direction-links="true" boundary-links="false" 
                total-items="userCtrl.recordsTotal" 
                ng-model="userCtrl.page"
                previous-text="‹" next-text="›" 
                items-per-page="userCtrl.pageSize" ng-change="userCtrl.reloadData()"
                rotate="true" 
                max-size="10" boundary-link-numbers="true" 
                class="pagination">
            </ul>
        </div>
    </div>
</div>





