<?php
$this->headTitle('Customers');

$this->mainMenu()->setActiveItemId('customers');

$this->mainMenu()->setSiteMapOverride('Customers');

if (!empty($this->permissions()->isGranted('Application\Controller\SalespeopleController', 'index'))) {
    $this->pageBreadcrumbs()->setItems([
        'Salespeople' => $this->url('salespeople', ['action' => 'index']),
        'Customers' => $this->url('customer', ['action' => 'view']),
    ]);
} else {
    $this->pageBreadcrumbs()->setItems([
        'Customers' => $this->url('customer', ['action' => 'view']),
    ]);
}
?>

<div class="around_datatables" ng-controller="CustomerTableController as customerCtrl">

    <?= $this->partial('partial/customer-table-header-tplt') ?>

    <div >
        <table datatable="customersTable" dt-instance="customerCtrl.dtInstanceCallback" dt-options="customerCtrl.dtOptions" dt-columns="customerCtrl.dtColumns" style="width: 100%;" class="table-bordered table-condensed table-hover table-striped">
            <thead>
                <tr class="no-padding">
                    <th>
                        <!-- ID -->
                    </th>
                    <th>
                        <div class='input-group'>
                        <input type="text" 
                               name="zff_company" 
                               placeholder="Company"
                               ffm-enter="customerCtrl.reloadData()" 
                               typeahead-on-select="customerCtrl.reloadData()"
                               ng-model="customerCtrl.zff_company" 
                               uib-typeahead="company for company in customerCtrl.companies | filter:$viewValue" 
                               typeahead-append-to-body="true"
                               class="filter form-control">
                            <span class="input-group-addon">
                                <span class="ion ion-search"></span>
                            </span>
                        </div>
                    </th>
                    <th>
                        <div class='input-group'>
                        <input type="text" 
                               name="zff_name" 
                               placeholder="Name"
                               ffm-enter="customerCtrl.reloadData()" 
                               typeahead-on-select="customerCtrl.reloadData()"
                               ng-model="customerCtrl.zff_name" 
                               uib-typeahead="name for name in customerCtrl.names | filter:$viewValue" 
                               typeahead-append-to-body="true"
                               class="filter form-control">
                            <span class="input-group-addon">
                                <span class="ion ion-search"></span>
                            </span>
                        </div>
                    </th>
                    <th>
                        <div class="input-group">
                        <input type="text" 
                               name="zff_email" 
                               placeholder="Email"
                               ffm-enter="customerCtrl.reloadData()" 
                               typeahead-on-select="customerCtrl.reloadData()"
                               ng-model="customerCtrl.zff_email" 
                               uib-typeahead="email for email in customerCtrl.emails | filter:$viewValue" 
                               typeahead-append-to-body="true"
                               class="filter form-control">
                            <span class="input-group-addon">
                                <span class="ion ion-search"></span>
                            </span>
                        </div>
                    </th>
                    <th>
                        <!-- CREATED -->
                        <label ng-click="customerCtrl.zff_created_open = true" class="cursor-pointer date-picker-table">
                            <input 
                                name="zff_created" 
                                ng-change="customerCtrl.reloadData()" 
                                readonly 
                                placeholder="Created"
                                datepicker-append-to-body="true" 
                                type="text" 
                                class="form_datetime filter form-control" 
                                uib-datepicker-popup="{{customerCtrl.dateformat}}" 
                                ng-model="customerCtrl.zff_created" 
                                is-open="customerCtrl.zff_created_open" 
                                datepicker-options="customerCtrl.dateOptions" 
                                alt-input-formats="customerCtrl.altInputFormats" />
                            <i class="ion-calendar" ></i>
                        </label>
                    </th>
                    <th>
                        <!-- UPDATED -->
                        <label ng-click="customerCtrl.zff_updated_open = true" class="cursor-pointer date-picker-table">
                            <input 
                                name="zff_updated" 
                                ng-change="customerCtrl.reloadData()" 
                                readonly 
                                datepicker-append-to-body="true" 
                                type="text" 
                                placeholder="Updated"
                                class="form_datetime filter form-control" 
                                uib-datepicker-popup="{{customerCtrl.dateformat}}" 
                                ng-model="customerCtrl.zff_updated" 
                                is-open="customerCtrl.zff_updated_open" 
                                datepicker-options="customerCtrl.dateOptions" 
                                alt-input-formats="customerCtrl.altInputFormats" />
                            <i class="ion-calendar" ></i>
                        </label>
                    </th>
                    <th>
                        <!-- ACTIONS -->
                    </th>
                </tr>
                <tr>
                    <th>ID</th>
                    <th>Company</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Created</th>
                    <th>Updated</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>