<?php
$this->headTitle('Sign in');

$this->mainMenu()->setActiveItemId('login');

$this->mainMenu()->setSiteMapOverride('Sign In');

$form->get('submit')->setAttributes([
            'class' => 'btn btn-primary'
        ]);

$form->get('username')->setAttributes([
            'class' => 'form-control',
            'placeholder' => 'jdoe',
            'required' => true,
            'autofocus' => true
        ])
        ->setLabelAttributes([
            'class' => 'sr-only'
        ]);

$form->get('password')->setAttributes([
            'class' => 'form-control',
            'placeholder' => 'Password',
            'required' => true,
        ])
        ->setLabelAttributes([
            'class' => 'sr-only'
        ]);

$form->prepare();
?>

<div class="login">
    
    <div class="page-header">
        <h1><?php echo $this->translate('Sign in'); ?></h1>
    </div>

    <?php echo $this->form()->openTag($form) ?>

    <div class="form-group">
        <?= $this->formLabel($form->get('username')); ?>
        <?= $this->formElement($form->get('username')); ?>
        <span style="color:red;"><?= $this->formElementErrors($form->get('username')); ?></span>                
    </div>
    
    <div class="form-group">
        <?= $this->formLabel($form->get('password')); ?>
        <?= $this->formElement($form->get('password')); ?>
        <span style="color:red;"><?= $this->formElementErrors($form->get('password')); ?></span>                
    </div>
    
    <?= $this->formElement($form->get('submit')); ?>

    <?php

    echo $this->form()->closeTag();

    if (!empty($this->loginErrorMessage)) :
        echo '<div class="alert alert-danger"><ul><li>' . $this->loginErrorMessage . '</li></ul></div>';
    endif;
    ?>


</div>