<?php
$this->headTitle('Change Password');

$this->mainMenu()->setActiveItemId('users');
$this->mainMenu()->setSiteMapOverride('Change Password');

$this->pageBreadcrumbs()->setItems([
    'Manage Users' => $this->url('users'),
    'Change Password' => $this->url('users', ['action' => 'change-password', 'id' => $user->getId()])
]);

$form->get('admin_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter admin password'
]);

$form->get('new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter new password'
]);

$form->get('confirm_new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Re-enter new password'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();
?>

<div id='change-password-page' class='form-page'>

    <div class='content-box'>
        <div class='row'>
            <div class='col-md-4 col-md-offset-4 no-left'>
                <h4>Change Password for <?= $this->escapeHtml($user->getEmail()) ?></h4>
            </div>
        </div>
    </div>



    <div class="row">

        <?= $this->form()->openTag($form); ?>

        <div class="col-md-4 col-md-offset-4 form-content-box">


            <div class="form-group">
                <?= $this->formLabel($form->get('admin_password')); ?>
                <?= $this->formElement($form->get('admin_password')); ?>
                <?= $this->formElementErrors($form->get('admin_password')); ?>                   
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('new_password')); ?>
                <?= $this->formElement($form->get('new_password')); ?>
                <?= $this->formElementErrors($form->get('new_password')); ?>                
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('confirm_new_password')); ?>
                <?= $this->formElement($form->get('confirm_new_password')); ?>
                <?= $this->formElementErrors($form->get('confirm_new_password')); ?>                          
            </div>


        </div>  
        <div class="col-md-4 col-md-offset-4 form-content-submit text-right">
            <input name="reset" id="resetbutton" class="btn reset-btn" value="Reset" type="reset">
            <?= $this->formElement($form->get('csrf')); ?>
            <?= $this->formElement($form->get('submit')); ?>
        </div>


        <?= $this->form()->closeTag(); ?>
    </div> 
</div> 

