<?php
$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Users' => $this->url('users'),
]);
?>

<h1>Manage Users</h1>

<p>
    <a class="btn btn-default" href="
       <?= $this->url('users', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New User
    </a>
</p>

<div id='tableContainer' class="zf-table-wrap">

</div>

<script>

    $("#tableContainer").zfTable('/users-table');

</script>

