<?php
$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('users');

$this->mainMenu()->setSiteMapOverride('Manage Users');

$this->pageBreadcrumbs()->setItems([
    'Manage Users' => $this->url('users'),
]);
?>

<div class="around_datatables" ng-controller="UsersTableController as userCtrl">

    <?= $this->partial('partial/users-table-header-tplt') ?>

    <div >
        <table datatable="usersTable" dt-instance="userCtrl.dtInstanceCallback" dt-options="userCtrl.dtOptions" dt-columns="userCtrl.dtColumns" style="width: 100%;" class="table-bordered table-condensed table-hover table-striped">
            <thead>
                <tr class="no-padding">
                    <th>
                        <!-- ID -->
                    </th>
                    <th>
                        <div class="input-group">
                            <input name="zff_username" 
                                   ffm-enter="userCtrl.reloadData()" 
                                   ng-model="userCtrl.zff_username" 
                                   class="filter form-control" 
                                   placeholder="Username" 
                                   type="text">
                            <span class="input-group-addon">
                                <span class="ion ion-search"></span>
                            </span>
                        </div>
                    </th>
                    <th>
                        <div class="input-group">
                        <input 
                            name="zff_email" 
                            ffm-enter="userCtrl.reloadData()" 
                            ng-model="userCtrl.zff_email" 
                            class="filter form-control" 
                            placeholder="Email" 
                            type="text">
                            <span class="input-group-addon">
                                <span class="ion ion-search"></span>
                            </span>
                        </div>
                    </th>
                    <th>
                        <div class="btn-group bootstrap-select filter form-control" uib-dropdown dropdown-append-to-body="true">
                            <ul class="dropdown-menu table-head" uib-dropdown-menu >
                                <li >
                                    <a href="#" ng-click="userCtrl.selectStatus('Active')">Active</a>
                                </li>
                                <li >
                                    <a href="#" ng-click="userCtrl.selectStatus('Inactive')">Inactive</a>
                                </li>
                            </ul>
                            <button id="single-button" type="button" class="btn btn-default" uib-dropdown-toggle >
                                <span ng-if="!userCtrl.status" class="filter-option pull-left">- Select -</span>
                                <span ng-if="userCtrl.status" class="filter-option pull-left">{{userCtrl.status}}</span>
                                &nbsp;
                                <span class="caret"></span>
                            </button>

                        </div>
                        <!-- STATUS -->

                    </th>
                    <th>
                        <div class='input-group'>
                        <input 
                            name="zff_fullname" 
                            ffm-enter="userCtrl.reloadData()" 
                            ng-model="userCtrl.zff_fullname" 
                            class="filter form-control" 
                            placeholder="Full Name" 
                            type="text">
                            <span class="input-group-addon">
                                <span class="ion ion-search"></span>
                            </span>
                        </div>
                    </th>
                    <th>
                        <!-- CREATED -->
                        <label ng-click="userCtrl.zff_createddate_open = true" class="cursor-pointer date-picker-table">
                            <input 
                                name="zff_createdDate" 
                                ng-change="userCtrl.reloadData()" 
                                readonly 
                                placeholder='Created'
                                datepicker-append-to-body="true" 
                                type="text" 
                                class="form_datetime filter form-control" 
                                uib-datepicker-popup="{{userCtrl.dateformat}}" 
                                ng-model="userCtrl.zff_createddate" 
                                is-open="userCtrl.zff_createddate_open" 
                                datepicker-options="userCtrl.dateOptions" 
                                alt-input-formats="userCtrl.altInputFormats" />
                            <i class="ion-calendar" ></i>
                        </label>
                    </th>
                    <th>
                        <!-- LAST LOGIN -->
                        <label ng-click="userCtrl.zff_lastlogindate_open = true" class="cursor-pointer date-picker-table">
                            <input 
                                name="zff_lastLogin" 
                                ng-change="userCtrl.reloadData()" 
                                readonly 
                                placeholder='Last Login'
                                datepicker-append-to-body="true" 
                                type="text" 
                                class="form_datetime filter form-control" 
                                uib-datepicker-popup="{{userCtrl.dateformat}}" 
                                ng-model="userCtrl.zff_lastlogindate" 
                                is-open="userCtrl.zff_lastlogindate_open" 
                                datepicker-options="userCtrl.dateOptions" 
                                alt-input-formats="userCtrl.altInputFormats" />
                            <i class="ion-calendar" ></i>
                        </label>
                    </th>
                    <th>
                        <!-- ACTIONS -->
                    </th>
                </tr>
                <tr>
                    <th>ID</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th>Fullname</th>
                    <th>Created</th>
                    <th>Last Login</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>




