<?php
$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Users' => $this->url('users'),
]);
?>

<h1>Manage Users</h1>

<p>
    <a class="btn btn-default" href="
       <?= $this->url('users', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New User
    </a>
</p>

<div id='tableContainer' class="zf-table-wrap">

</div>

<script>

    $("#tableContainer").zfTable('/users-table', {
      complete: function () {
        console.log('complete');
        $('#usersTable tr').each(function (index, element) {
          var id = $(this).children('td').first().html();
          if (id) {
            var html = new Array();
            html.push('<div class="around-table-actions"><a class="btn btn-default btn-square btn-transparent" title="Edit User" href="users/edit/' + id);
            html.push('"><i class="ion ion-edit spin-logo"></i></a>');
            //html.push('"><img src="/img/pencil-icon.svg" alt="" class="settings-logo"/></a>');
            html.push('<a class="btn btn-default  btn-square btn-transparent" title="Change User Password" href=');
            html.push('"users/change-password/' + id + '">');
            html.push('<i class="ion ion-locked spin-logo"></i></a></div>');
            $(this).children('td').last().html(html.join(''));
          }
        });
      }
    });

</script>
