<?php
$this->headTitle('View User');

$this->mainMenu()->setActiveItemId('users');

$this->mainMenu()->setSiteMapOverride('View User');

$this->pageBreadcrumbs()->setItems([
            'Manage Users'=>$this->url('users'),
            'View User'=>$this->url('users', ['action'=>'view', 'id'=>$user->getId()])
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>View User</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <th><?= $this->escapeHtml($user->getId()) ?></th>
            </tr>
            <tr>
                <th>Username:</th>
                <th><?= $this->escapeHtml($user->getUsername()) ?></th>
            </tr>
            <tr>
                <th>E-mail:</th>
                <th><?= $this->escapeHtml($user->getEmail()) ?></th>
            </tr>
            <tr>
                <th>Full Name:</th>
                <th><?= $this->escapeHtml($user->getFullName()) ?></th>
            </tr>
            <tr>
                <th>Date Created:</th>
                <th><?= $this->escapeHtml(date_format($user->getDateCreated(), 'm/d/Y')) ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <th><?= $this->escapeHtml($user->getStatusAsString()) ?></th>
            </tr>
        </table>
    </div>
</div>