<?php
$this->headTitle('Product');

if (!empty($this->permissions()->isGranted('Application\Controller\SalespeopleController', 'index'))) {
    $this->pageBreadcrumbs()->setItems([
        'Salespeople' => $this->url('salespeople', ['action' => 'index']),
        'Customers' => $this->url('customer', ['action' => 'index']),
        'Products' => $this->url('product', ['action' => 'index']),
    ]);
} else {
    $this->pageBreadcrumbs()->setItems([
        'Customers' => $this->url('customer', ['action' => 'index']),
        'Products' => $this->url('product', ['action' => 'index']),
    ]);
}
?>

<div class="around_datatables" ng-controller="ProductTableController as productCtrl">
    
    <?= $this->partial('partial/product-table-header-tplt') ?>

    <div >
        <table datatable="productsTable" dt-instance="productCtrl.dtInstanceCallback" dt-options="productCtrl.dtOptions" dt-columns="productCtrl.dtColumns" style="width: 100%;" class="table-bordered table-condensed table-hover table-striped">
            <thead>
                <tr class="no-padding">
                    <th>
                        <!-- ID -->
                    </th>
                    <th>
                        <!-- USERNAME -->
                        <input name="zff_username" ffm-enter="productCtrl.reloadData()" ng-model="productCtrl.zff_username" class="filter form-control" value="" type="text">
                    </th>
                    <th>
                        <!-- EMAIL -->
                        <input name="zff_email" ffm-enter="productCtrl.reloadData()" ng-model="productCtrl.zff_email" class="filter form-control" value="" type="text">
                    </th>
                    <th>
                        <div class="btn-group bootstrap-select filter form-control" uib-dropdown dropdown-append-to-body="true">
                            <ul class="dropdown-menu table-head" uib-dropdown-menu >
                                <li >
                                    <a href="#" ng-click="productCtrl.selectStatus('Active')">Active</a>
                                </li>
                                <li >
                                    <a href="#" ng-click="productCtrl.selectStatus('Inactive')">Inactive</a>
                                </li>
                            </ul>
                            <button id="single-button" type="button" class="btn btn-default" uib-dropdown-toggle >
                                <span ng-if="!productCtrl.status" class="filter-option pull-left">- Select -</span>
                                <span ng-if="productCtrl.status" class="filter-option pull-left">{{productCtrl.status}}</span>
                                &nbsp;
                                <span class="caret"></span>
                            </button>

                        </div>
                        <!-- STATUS -->

                    </th>
                    <th>
                        <!-- FULL NAME -->
                        <input name="zff_fullname" ffm-enter="productCtrl.reloadData()" ng-model="productCtrl.zff_fullname" class="filter form-control" value="" type="text">
                    </th>
                    <th>
                        <!-- CREATED -->
                        <label ng-click="productCtrl.zff_createddate_open = true" class="cursor-pointer date-picker-table">
                            <input name="zff_createdDate" ng-change="productCtrl.reloadData()" readonly datepicker-append-to-body="true" type="text" class="form_datetime filter form-control" uib-datepicker-popup="{{productCtrl.dateformat}}" ng-model="productCtrl.zff_createddate" is-open="productCtrl.zff_createddate_open" datepicker-options="productCtrl.dateOptions" alt-input-formats="productCtrl.altInputFormats" />
                            <i class="ion-calendar" ></i>
                        </label>
                    </th>
                    <th>
                        <!-- LAST LOGIN -->
                        <label ng-click="productCtrl.zff_lastlogindate_open = true" class="cursor-pointer date-picker-table">
                            <input name="zff_lastLogin" ng-change="productCtrl.reloadData()" readonly datepicker-append-to-body="true" type="text" class="form_datetime filter form-control" uib-datepicker-popup="{{productCtrl.dateformat}}" ng-model="productCtrl.zff_lastlogindate" is-open="productCtrl.zff_lastlogindate_open" datepicker-options="productCtrl.dateOptions" alt-input-formats="productCtrl.altInputFormats" />
                            <i class="ion-calendar" ></i>
                        </label>
                    </th>
                    <th>
                        <!-- ACTIONS -->
                    </th>
                </tr>
                <tr>
                    <th>ID</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th>Fullname</th>
                    <th>Created</th>
                    <th>Last Login</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody></tbody>
            <tfoot>
                <tr>
                    <th>ID</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th>Fullname</th>
                    <th>Created</th>
                    <th>Last Login</th>
                    <th>Actions</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>