<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/pricing-logo.ico'])
                ->prependStylesheet($this->basePath('css/dist/style.css'))
                ->prependStylesheet($this->basePath() . 'css/zf-table.css')
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath() . 'css/zf-table.css')
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/dist/vendor.js'))
        ?>
    </head>
    <body>
        <!-- Navigation bar -->
        <?php
        // Check if the activeMenuItemId passed to layout view model
        // and if so, use it for setting active navbar item.
        if (isset($activeMenuItemId)) {
            $this->mainMenu()->setActiveItemId($activeMenuItemId);
        }

        // Render the navbar
        echo $this->mainMenu()->render();
        
        // Render the Breadcrumbs
        echo $this->pageBreadcrumbs()->render();
        
        ?>
        
        <div class="container main">

            <?php echo $this->content; ?>



        </div> 
        <footer>
            <p> <?php echo $this->translate('Fulton Fish Market - Skeleton App') ?>&nbsp; <?php echo date('Y') ?> Meade Digital Enterprises </p>
        </footer>
        <?= $this->inlineScript() ?>
    </body>

</html>
