<form id="add_product_form" method="post" name="addProductForm">
    <div class="modal-header">
        <div class="container">
            <div class="row">
                <div class="pull-left col-md-11 col-lg-11 col-sm-11">
                    <h3>Add Product</h3>
                </div>
                <a class="pull-right modal-icon ion-ios-close-outline" data-dismiss="modal" ng-click="vmc.cancel()"></a>
            </div>
        </div>
    </div>
    <div class="modal-body" id="modal-body">
        <div class="container">
            <div class="form-group" >
                <div class="row">

                    <!--Left Column on md or lg-->
                    <div class="col-sm-12 col-md-6 col-lg-6 row">
                        <!--Product-->
                        <div class="col-sm-12" ng-class="{'comment col-md-12 col-lg-12': true}">
                            <label class="control-label" ng-bind="vmc.label.product"></label>
                            <div class="input-group col-sm-12 col-md-12 col-lg-12" ng-class="{'has-error': !addProductForm.product.$valid && addProductForm.product.$touched}">

                                <!--<input class="form-control" ng-required="true" ng-model="vmc.product" placeholder="Product" name="product" type="text" select-on-focus>-->
                                <input id='products-typeahead' type="text" 
                                       name="product"
                                       placeholder="Product"
                                       ng-model="vmc.typeaheadProduct" 
                                       typeahead-on-select="vmc.selectProduct()"
                                       uib-typeahead="stuff as stuff.productname for stuff in vmc.getTypeaheadProducts($viewValue)" 
                                       autocomplete="off"
                                       class="filter form-control"
                                       select-on-focus
                                       >

                            </div>
                        </div>
                        <!--Description-->
                        <div class="col-sm-12" ng-class="{'comment col-md-12 col-lg-12': true}">
                            <label class="control-label" ng-bind="vmc.label.description"></label>
                            <div class="input-group col-sm-12 col-md-12 col-lg-12" ng-class="{'has-error': !addProductForm.description.$valid && addProductForm.description.$touched}">
                                <input class="form-control" ng-model="vmc.product.description" placeholder="Description" name="description" type="text" select-on-focus>
                            </div>
                        </div>
                        <!--Comment-->
                        <div class="col-sm-12" ng-class="{'comment col-md-12 col-lg-12': true}">
                            <label class="control-label" ng-bind="vmc.label.comment"></label>
                            <div class="input-group col-sm-12 col-md-12 col-lg-12" ng-class="{'has-error': !addProductForm.comment.$valid && addProductForm.comment.$touched}">
                                <input class="form-control" ng-model="vmc.comment" placeholder="Comment" name="comment" type="text" select-on-focus>
                            </div>
                        </div>
                    </div>

                    <!--Right Column on md or lg-->
                    <div class="col-sm-12 col-md-6 col-lg-6 row">
                        <!--Override Price-->
                        <!--
                            When form is submitted with no overrideprice value - then we remove the associated
                            overrideprice record (set to Inactive)
                        -->
                        <div class="col-sm-12" ng-class="{'comment col-md-12 col-lg-12': true}">
                            <label class="control-label" ng-bind="vmc.label.overrideprice"></label>
                            <div class="input-group col-sm-12 col-md-12 col-lg-12" ng-class="{'has-error': !addProductForm.overrideprice.$valid && addProductForm.overrideprice.$touched}">
                                <input class="form-control" 
                                       ng-pattern="vmc.pattern.money" 
                                       ffm-validate-money 
                                       ng-model="vmc.product.retail" 
                                       placeholder="Override Price" 
                                       name="overrideprice" 
                                       type="text" 
                                       select-on-focus>
                                <div ng-messages="addProductForm.overrideprice.$error">
                                    <div ng-message="boundsLow">Override price must be more than $.29</div>
                                    <div ng-message="boundsHigh">Override price must be less than $30000</div>
                                </div>
                            </div>
                        </div>
                        <!--UOM-->
                        <div class="col-sm-12" ng-class="{'comment col-md-12 col-lg-12': true}">
                            <label class="control-label" ng-bind="vmc.label.uom"></label>
                            <div class="input-group col-sm-12 col-md-12 col-lg-12" ng-class="{'has-error': !addProductForm.uom.$valid && addProductForm.uom.$touched}">
                                <input class="form-control" ng-required="true" ng-model="vmc.product.uom" placeholder="Unit of Measure" name="uom" type="text" select-on-focus>
                            </div>
                        </div>
                        <!--SKU-->
                        <div class="col-sm-12" ng-class="{'comment col-md-12 col-lg-12': true}" >
                            <label class="control-label" ng-bind="vmc.label.sku"></label>
                            <div class="input-group col-sm-12 col-md-12 col-lg-12" ng-class="{'has-error': !addProductForm.sku.$valid && addProductForm.sku.$touched}">
                                <input class="form-control" ng-pattern="vmc.pattern.sku" ng-model="vmc.product.sku" placeholder="SKU" name="sku" type="text" select-on-focus>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <div class="container">
            <div class="row">
                <button class="btn reset-btn" type="button" data-dismiss="modal" ng-click="vmc.cancel()">
                    Cancel
                </button>
                <button class="row-save btn btn-primary" ng-click="vmc.ok(
                            addProductForm.product.$valid &&
                            addProductForm.description.$valid &&
                            addProductForm.comment.$valid &&
                            addProductForm.overrideprice.$valid &&
                            addProductForm.uom.$valid &&
                            addProductForm.sku.$valid
                            )">
                    Save
                </button>
            </div>
        </div>
    </div>
</form>
