<div class="table-header" >
    <div class="pull-left">
        <header>
            <h4 uib-popover="{{customerCtrl.tableTitle()}}" 
                popover-placement="bottom" 
                popover-trigger="'mouseenter'" 
                class="table-header-item ffs-remove">
                Customers
                <span class="table-header-item">(</span>
                <span class="table-header-item" ng-bind="customerCtrl.recordsFiltered"></span>
                <span class="table-header-item">/</span>
                <span class="table-header-item" ng-bind="customerCtrl.recordsTotal"></span>
                <span class="table-header-item">)</span>
            </h4>
        </header>
    </div>

    <div class="pull-right">
        
        <?php if (!empty($this->permissions()->isGranted('Application\Controller\SalespeopleController', 'index'))): ?>

            <a class="table-header-btn reset-filters-btn btn-default"
                uib-popover="Go to Salespeople" 
                popover-placement="bottom" 
                popover-trigger="'mouseenter'"
                href="/salespeople">
                <span class="ffs-remove" ng-bind="customerCtrl.salesperson"></span>
                <i class="ion-person"></i>
            </a>

        <?php endif; ?>

        <a class="table-header-btn reset-filters-btn btn-default" title="Reset Filters" ng-click="customerCtrl.resetFilters()"> 
            Reset all filters
            <i class="ion-close"></i>
        </a>

        <div class="btn-group bootstrap-select itemPerPage form-control" uib-dropdown>

            <button class="btn dropdown-toggle btn-default" type="button" 
                    uib-dropdown-toggle ng-title="customerCtrl.pageSize" >

                <span class="filter-option pull-left"> 
                    {{customerCtrl.pageSize}}
                </span>

                <span class="caret"></span>

            </button>

            <ul class="dropdown-menu" uib-dropdown-menu role="menu" >
                <li >
                    <a href="#" ng-click="customerCtrl.selectPageSize(customerCtrl.pageSizes[0])" ng-bind="customerCtrl.pageSizes[0]"></a>
                </li>
                <li >
                    <a href="#" ng-click="customerCtrl.selectPageSize(customerCtrl.pageSizes[1])" ng-bind="customerCtrl.pageSizes[1]"></a>
                </li>
                <li >
                    <a href="#" ng-click="customerCtrl.selectPageSize(customerCtrl.pageSizes[2])" ng-bind="customerCtrl.pageSizes[2]"></a>
                </li>
                <li >
                    <a href="#" ng-click="customerCtrl.selectPageSize(customerCtrl.pageSizes[3])" ng-bind="customerCtrl.pageSizes[3]"></a>
                </li>
                <li >
                    <a href="#" ng-click="customerCtrl.selectPageSize(customerCtrl.pageSizes[4])" ng-bind="customerCtrl.pageSizes[4]"></a>
                </li>
            </ul>

        </div>

        <div class="table-header-text">Customers</div>

        <div class="dataTables_paginate paging_bootstrap pull-right">

            <ul uib-pagination direction-links="true" boundary-links="false" 
                total-items="customerCtrl.recordsTotal" 
                ng-model="customerCtrl.page" 
                previous-text="‹" next-text="›" 
                items-per-page="customerCtrl.pageSize" ng-change="customerCtrl.reloadData()"
                rotate="true" 
                max-size="5" boundary-link-numbers="true" 
                class="pagination">
            </ul>
        </div>
    </div>
</div>





