<form id="add_product_form" method="post" name="addOverridePriceForm">
    <div class="modal-header">
        <div class="container">
            <div class="row">
                <div class="pull-left col-md-11 col-lg-11 col-sm-11">
                    <h3 ng-bind="vmc.scenario === 'create' ? 'Add Override Price' : 'Edit Override Product'"></h3>
                </div>
                <a class="pull-right modal-icon ion-ios-close-outline" data-dismiss="modal" ng-click="vmc.cancel()"></a>
            </div>
        </div>
    </div>
    <div class="modal-body" id="modal-body">
        <div class="container" style="font-family: 'Roboto' !important;">
            <div class="form-group" >
                <div class="row">
                    <!--Left Column on md or lg-->
                    <div class="col-sm-12 ion col-md-12 col-lg-12 row">
                        <!--Override Price-->
                        <div class="col-sm-12" ng-class="{'comment col-md-12 col-lg-12': true}">
                            <label class="control-label" ng-bind="vmc.label.overrideprice"></label>
                            <div class="input-group col-sm-12 col-md-12 col-lg-12" ng-class="{'has-error': !addOverridePriceForm.overrideprice.$valid && addOverridePriceForm.overrideprice.$touched}">
                                <input class="form-control" ng-required="false" ng-pattern="vmc.pattern.money" ng-model="vmc.overrideprice" placeholder="Override Price" name="overrideprice" type="text" select-on-focus>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <div class="container">
            <div class="row">
                <button class="btn reset-btn" type="button" data-dismiss="modal" ng-click="vmc.cancel()">
                    Cancel
                </button>
                <button class="row-save btn btn-primary" ng-click="vmc.ok(addOverridePriceForm.overrideprice.$valid)">
                    Save
                </button>
            </div>
        </div>
    </div>
</form>

