<div class="table-header product-table-header" >
    <div class="pull-left">
        <header>
            <div class="pull-left header-item-wrapper">
                <h4 uib-popover="{{productCtrl.tableTitle()}}" 
                    popover-placement="bottom" 
                    popover-trigger="'mouseenter'" 
                    class="table-header-item">
                    Products
                    <span class="table-header-item">(</span>
                    <span class="table-header-item" ng-bind="productCtrl.recordsFiltered"></span>
                    <span class="table-header-item">/</span>
                    <span class="table-header-item" ng-bind="productCtrl.recordsTotal"></span>
                    <span class="table-header-item">)</span>
                </h4>
            </div>
        </header>
    </div>

    <div id="pdf-container" 
         class="pull-right">

        <?php if (!empty($this->permissions()->isGranted('Application\Controller\SalespeopleController', 'index'))): ?>

            <a uib-popover="Go to Salespeople" 
               popover-placement="bottom" 
               popover-trigger="'mouseenter'" 
               class="table-header-btn reset-filters-btn btn-accent" href="/salespeople"> 
                <span class="ffs-remove" ng-bind="productCtrl.salesperson"></span>
                <i class="ion-person"></i>
            </a>

        <?php endif; ?>

        <a uib-popover="Go to Customers" 
           popover-placement="bottom" 
           popover-trigger="'mouseenter'" 
           class="table-header-btn reset-filters-btn btn-accent" 
           href="/customer">
            <span class="ffs-remove" ng-bind="productCtrl.company"></span>
            <i class="ion-fork"></i>
        </a>

        <a uib-popover="Go to Customers" 
           popover-placement="bottom" 
           popover-trigger="'mouseenter'" 
           class="table-header-btn reset-filters-btn btn-accent" 
           href="/customer">
            <span class="ffs-remove" ng-bind="productCtrl.name"></span>
            <i class="ion-person"></i>
        </a>

        <a id="add_product_button" uib-popover="Add Product" 
               popover-placement="bottom" 
               popover-trigger="'mouseenter'" 
               ng-click="productCtrl.addProduct()" 
               class="table-header-btn reset-filters-btn btn-accent" title="Add Product" href="#">
                Add Product
                <i class="ion-plus"></i>
               
            </a>

        <a class="table-header-btn reset-filters-btn btn-default" title="Reset Filters" ng-click="productCtrl.resetFilters()"> 
            Reset all filters
            <i class="ion-close"></i>
        </a>

        <div class="btn-group bootstrap-select itemPerPage form-control" uib-dropdown>

            <button class="btn dropdown-toggle btn-default" type="button" 
                    uib-dropdown-toggle ng-title="productCtrl.pageSize" >

                <span class="filter-option pull-left"> 
                    {{productCtrl.pageSize}}
                </span>

                <span class="caret"></span>

            </button>

            <ul class="dropdown-menu" uib-dropdown-menu role="menu" >
                <li >
                    <a href="#" ng-click="productCtrl.selectPageSize(productCtrl.pageSizes[0])" ng-bind="productCtrl.pageSizes[0]"></a>
                </li>
                <li >
                    <a href="#" ng-click="productCtrl.selectPageSize(productCtrl.pageSizes[1])" ng-bind="productCtrl.pageSizes[1]"></a>
                </li>
                <li >
                    <a href="#" ng-click="productCtrl.selectPageSize(productCtrl.pageSizes[2])" ng-bind="productCtrl.pageSizes[2]"></a>
                </li>
                <li >
                    <a href="#" ng-click="productCtrl.selectPageSize(productCtrl.pageSizes[3])" ng-bind="productCtrl.pageSizes[3]"></a>
                </li>
                <li >
                    <a href="#" ng-click="productCtrl.selectPageSize(productCtrl.pageSizes[4])" ng-bind="productCtrl.pageSizes[4]"></a>
                </li>
            </ul>

        </div>

        <div class="table-header-text">Product</div>

        <div class="dataTables_paginate paging_bootstrap pull-right">

            <ul uib-pagination direction-links="true" boundary-links="false" 
                total-items="productCtrl.recordsFiltered" 
                ng-model="productCtrl.page" 
                previous-text="‹" next-text="›" 
                items-per-page="productCtrl.pageSize" ng-change="productCtrl.reloadData()"
                rotate="true" 
                max-size="5" boundary-link-numbers="true" 
                class="pagination">
            </ul>
        </div>
    </div>
</div>





