<div class="table-header" >
    <div class="pull-left">
        <header>
            <h4 class="pull-left">
                Products (<span ng-bind="productCtrl.recordsFiltered"></span>)

                <?php if (!empty($this->permissions()->isGranted('Application\Controller\ProductController', 'add'))): ?>

                    <span >
                        <a class="ion-plus" title="Add Product" href="#"></a>
                    </span>

                <?php endif; ?>
            </h4>
        </header>
    </div>

    <div class="pull-right">
        
        <a class="table-header-btn reset-filters-btn btn-default" title="Reset Filters" ng-click="productCtrl.resetFilters()"> 
            Reset all filters
            <i class="ion-close"></i>
        </a>

        <div class="btn-group bootstrap-select itemPerPage form-control" uib-dropdown>

            <button class="btn dropdown-toggle btn-default" type="button" 
                    uib-dropdown-toggle ng-title="productCtrl.pageSize" >

                <span class="filter-option pull-left"> 
                    {{productCtrl.pageSize}}
                </span>

                <span class="caret"></span>

            </button>

            <ul class="dropdown-menu" uib-dropdown-menu role="menu" >
                <li >
                    <a href="#" ng-click="productCtrl.selectPageSize(2)">2</a>
                </li>
                <li >
                    <a href="#" ng-click="productCtrl.selectPageSize(10)">10</a>
                </li>
                <li >
                    <a href="#" ng-click="productCtrl.selectPageSize(25)">25</a>
                </li>
                <li >
                    <a href="#" ng-click="productCtrl.selectPageSize(50)">50</a>
                </li>
                <li >
                    <a href="#" ng-click="productCtrl.selectPageSize(100)">100</a>
                </li>
            </ul>

        </div>

        <div class="table-header-text">Product</div>

        <div class="dataTables_paginate paging_bootstrap pull-right">

            <ul uib-pagination direction-links="true" boundary-links="false" 
                total-items="productCtrl.recordsTotal" 
                ng-model="productCtrl.page" 
                previous-text="‹" next-text="›" 
                items-per-page="productCtrl.pageSize" ng-change="productCtrl.reloadData()"
                rotate="true" 
                max-size="5" boundary-link-numbers="true" 
                class="pagination">
            </ul>
        </div>
    </div>
</div>





