<div class="table-header" >
    <div class="pull-left">
        <header>
            <h4 class="pull-left">
                Salespeople (<span ng-bind="salespeopleCtrl.recordsFiltered"></span>)
            </h4>
        </header>
    </div>

    <div class="pull-right">

        <a ng-if="salespeopleCtrl.missingFromWebServiceSalespeople.length > 0" ng-repeat="salesperson in salespeopleCtrl.missingFromWebServiceSalespeople track by $index" 
           class="table-header-btn reset-filters-btn btn-accent" uib-popover="{{salesperson['full_name']}} not found in Web Service" popover-placement="bottom" popover-trigger="'mouseenter'" ng-click="salespeopleCtrl.addSalesperson('missingFromWebServiceSalespeople', $index)"
           ng-bind="salesperson['full_name']">
           
            <i class="ion-edit"></i>
        </a>
        
        <a ng-if="salespeopleCtrl.missingFromDBSalespeople.length > 0" ng-repeat="salesperson in salespeopleCtrl.missingFromDBSalespeople track by $index" 
           class="table-header-btn reset-filters-btn btn-accent" uib-popover="{{salesperson['full_name']}} inactive salesperson returned by Web Service" popover-placement="bottom" popover-trigger="'mouseenter'" ng-click="salespeopleCtrl.addSalesperson('missingFromDBSalespeople', $index)"
           ng-bind="salesperson['full_name']">
            <i class="ion-plus"></i>
        </a>

        <a uib-popover="Reset all page filters and re-populate results" class="table-header-btn reset-filters-btn btn-default" ng-click="salespeopleCtrl.resetFilters()"> 
            Reset all filters
            <i class="ion-close"></i>
        </a>

        <div class="btn-group bootstrap-select itemPerPage form-control" uib-dropdown>

            <button class="btn dropdown-toggle btn-default" type="button" 
                    uib-dropdown-toggle title="Set Page Size" >

                <span class="filter-option pull-left" ng-bind="salespeopleCtrl.pageSize"> 
                    
                </span>

                <span class="caret"></span>

            </button>

            <ul class="dropdown-menu" uib-dropdown-menu role="menu" >
                <li >
                    <a href="#" ng-click="salespeopleCtrl.selectPageSize(salespeopleCtrl.pageSizes[0])" ng-bind="salespeopleCtrl.pageSizes[0]"></a>
                </li>
                <li >
                    <a href="#" ng-click="salespeopleCtrl.selectPageSize(salespeopleCtrl.pageSizes[1])" ng-bind="salespeopleCtrl.pageSizes[1]"></a>
                </li>
                <li >
                    <a href="#" ng-click="salespeopleCtrl.selectPageSize(salespeopleCtrl.pageSizes[2])" ng-bind="salespeopleCtrl.pageSizes[2]"></a>
                </li>
                <li >
                    <a href="#" ng-click="salespeopleCtrl.selectPageSize(salespeopleCtrl.pageSizes[3])" ng-bind="salespeopleCtrl.pageSizes[3]"></a>
                </li>
                <li >
                    <a href="#" ng-click="salespeopleCtrl.selectPageSize(salespeopleCtrl.pageSizes[4])" ng-bind="salespeopleCtrl.pageSizes[4]"></a>
                </li>
            </ul>

        </div>

        <div class="table-header-text">Salespeople</div>

        <div class="dataTables_paginate paging_bootstrap pull-right">

            <ul uib-pagination direction-links="true" boundary-links="false" 
                total-items="salespeopleCtrl.recordsTotal" 
                ng-model="salespeopleCtrl.page"
                previous-text="‹" next-text="›" 
                items-per-page="salespeopleCtrl.pageSize" ng-change="salespeopleCtrl.reloadData()"
                rotate="true" 
                max-size="10" boundary-link-numbers="true" 
                class="pagination">
            </ul>
        </div>
    </div>
</div>





