<?php if ($this->pageCount): ?>
    <div class="divider"></div>
    <ul class="pagination">
        <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
            <a data-page="<?php echo $this->previous?>">&lsaquo;</a></li>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>>
                <a data-page="<?php echo $page?>">
                    <?php echo $page; ?>
                </a>
            </li>
        <?php endforeach; ?>
        <!-- Next page link -->
        <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
            <a data-page="<?php echo $this->next?>">&rsaquo;</a></li>
    </ul>
<?php endif; ?>
