<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>

<h1>Welcome</h1>

<p>
    This is the Fulton Skeleton Application.
</p>

<div>
    
    Click the <em>Sign in</em> button at the top right. To sign in. You must have an account. If you 
    do not have an account, you must have an administrator create one for you.
    
</div>



