<?php
$this->headTitle('My Account');

$this->mainMenu()->setActiveItemId('settings');

$this->mainMenu()->setSiteMapOverride('My Account');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'My Account'=>$this->url('application', ['action'=>'settings']),
            ]);
?>

<div class='form-page'>

    <div class='content-box'>
        <div class='row'>
            <div class='col-md-4 col-md-offset-4 no-left'>
                <h4>My Account</h4>
            </div>
        </div>
    </div>



    <div class="row">
        
        <div class="col-md-4 col-md-offset-4 form-content-box">


            <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></th>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($user->getUsername()) ?></th>
            </tr>
            <tr>
                <th>Full Name:</th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></th>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></th>
            </tr>
        </table>


        </div>
    </div> 
</div> 